# yolo_mapping.py

YOLO_TO_APP_OBJECT = {
    "chair": "chair",
    "dining table": "desk",
    "bottle": "bottle",
    "backpack": "backpack",
    "laptop": "laptop",
    "couch": "couch",
    "tv": "tv",
    "keyboard": "keyboard",
    "mouse": "mouse",
    "remote": "remote",
    "cell phone": "phone",
    "cup": "cup",
    "potted plant": "plant",
    "book": "book",
    "clock": "clock",
    "vase": "vase",
    "scissors": "scissors",
    "teddy bear": "toy",
    "hair drier": "hair dryer",
    "toothbrush": "toothbrush",
    "wine glass": "glass",
    "fork": "fork",
    "knife": "knife",
    "spoon": "spoon",
    "bowl": "bowl",
    "banana": "banana",
    "apple": "apple",
    "orange": "orange",
    "pizza": "pizza",
    "cake": "cake",
    "handbag": "bag",
    "umbrella": "umbrella",
    "suitcase": "suitcase",
    "skateboard": "skateboard",
    "sports ball": "ball",
    # Weitere Labels nach Bedarf
}
